### ISSUE TITLE
Cannot find name 'OnInit'.

### ISSUE THREAD

**Issue by tbertenshaw** [johnpapa/angular2-force#1]
npm install
npm start

and i get the error (on windows)
app/heroes/hero.component.ts(10,39): error TS2304: Cannot find name 'OnInit'.

What have i done wrong?

using
(node v4.3.1
npm v3.8.8)

**Comment by nate2086** [comment]
If you go into the `hero.component.ts` component, you can remove the `implements OnInit`. John doesn't use OnInit in the component so it does no harm to remove. Once you do that you should be able to run the `npm start`.

I'm using Node 6, but once I removed that line everything worked.

**Comment by johnpapa** [comment]
closed with #2

**Comment by hiteshsahu** [comment]
Adding imports for lifecycle solved my issue.

`import { Component, OnInit, ViewEncapsulation } from '@angular/core';`

**Comment by TymidSympa** [comment]
mon probleme n'est pas toujours resolu malgre vos solutions proposés

ts2304: cannot find name 'OnInit'
